### ISSUE TITLE
type used in a using statement must be implicitly convertible to 'System.IDisposable'

### ISSUE THREAD

**Issue by sangyuxiaowu** [dahall/WinClassicSamplesCS#1]
use last Vanara.PInvoke.CldApi and Vanara.PInvoke.SearchApi

in file `CloudMirror\ContextMenus.cs`
```
using var fullPath = pShellItem.Item.GetDisplayName(SIGDN.SIGDN_FILESYSPATH);
```

Compiler Error CS1674

'T': type used in a using statement must be implicitly convertible to 'System.IDisposable'

**Comment by dahall** [comment]
That line, as you have written, isn't in the source code. The closest one I could find was:
https://github.com/dahall/WinClassicSamplesCS/blob/d8f54f2f45e68043f6a0be0442c7fb43ab18716a/CloudMirror/ContextMenus.cs#L89
Did it get modified in your fork/download? It compiles without error on my system.

**Comment by sangyuxiaowu** [comment]
I just upgraded the dependency of nuget and there was an error

I will check it again, maybe the version of the code I pulled is inconsistent.

**Comment by sangyuxiaowu** [comment]
I'm sorry to trouble you.
I updated the dependency package of nuget. Maybe because of network problems, the code I pulled yesterday was not the latest one. If I use the latest code, there is no such problem.

**Comment by sangyuxiaowu** [comment]
But there are other errors in this case. When I run this demo again, I cannot open the synchronized files.

```
Press ctrl-C to stop gracefully
-------------------------------
Succesfully called AddFolderToSearchIndexer on "file:///H:\ee"
Creating placeholder for wuxia_client 2018-03-29 20-47-08-167.png
Applying custom state for wuxia_client 2018-03-29 20-47-08-167.png
Creating placeholder for wuxia_client 2018-03-29 20-51-47-081.png
Applying custom state for wuxia_client 2018-03-29 20-51-47-081.png
[1E04:2488]-Received data request from \Device\HarddiskVolume9\Windows\explorer.exe for H:\ee\wuxia_client 2018-03-29 20-47-08-167.png, priority 5, offset 0000000000000000 length 000000000018B187
[1E04:2488]-Downloading data for H:\ee\wuxia_client 2018-03-29 20-47-08-167.png, priority 5, offset 0000000000000000 length 00001000
Succesfully called CfReportProviderProgress "H:\ee\wuxia_client 2018-03-29 20-47-08-167.png" with 4096/1622407
Failed to Set Transfer Progress on "H:\ee\wuxia_client 2018-03-29 20-47-08-167.png" with 80004002
[1E04:2488]-Executing download for H:\ee\wuxia_client 2018-03-29 20-47-08-167.png, Status 00000000, priority 5, offset 0000000000000000 length 00001000
```

in `CloudMirror\FileCopierWithProgress.cs` line 257
`CfExecute(opInfo, ref opParams).ThrowIfFailed();`

System.ArgumentException:“Value does not fall within the expected range.”

```
Unhandled exception. System.ArgumentException: Value does not fall within the expected range.
   at Vanara.PInvoke.HRESULT.ThrowIfFailed(String message)
   at CloudMirror.FileCopierWithProgress.TransferData(CF_CONNECTION_KEY connectionKey, CF_TRANSFER_KEY transferKey, IntPtr transferData, Int64 startingOffset, Int64 length, NTStatus completionStatus) in CloudMirror\FileCopierWithProgress.cs:line 257
   at CloudMirror.FileCopierWithProgress.OverlappedCompletionRoutine(UInt32 errorCode, UInt32 numberOfBytesTransfered, NativeOverlapped* overlapped) in CloudMirror\FileCopierWithProgress.cs:line 190
```

**Comment by hellojayjay** [comment]
> But there are other errors in this case. When I run this demo again, I cannot open the synchronized files.
> 
> ```
> Press ctrl-C to stop gracefully
> -------------------------------
> Succesfully called AddFolderToSearchIndexer on "file:///H:\ee"
> Creating placeholder for wuxia_client 2018-03-29 20-47-08-167.png
> Applying custom state for wuxia_client 2018-03-29 20-47-08-167.png
> Creating placeholder for wuxia_client 2018-03-29 20-51-47-081.png
> Applying custom state for wuxia_client 2018-03-29 20-51-47-081.png
> [1E04:2488]-Received data request from \Device\HarddiskVolume9\Windows\explorer.exe for H:\ee\wuxia_client 2018-03-29 20-47-08-167.png, priority 5, offset 0000000000000000 length 000000000018B187
> [1E04:2488]-Downloading data for H:\ee\wuxia_client 2018-03-29 20-47-08-167.png, priority 5, offset 0000000000000000 length 00001000
> Succesfully called CfReportProviderProgress "H:\ee\wuxia_client 2018-03-29 20-47-08-167.png" with 4096/1622407
> Failed to Set Transfer Progress on "H:\ee\wuxia_client 2018-03-29 20-47-08-167.png" with 80004002
> [1E04:2488]-Executing download for H:\ee\wuxia_client 2018-03-29 20-47-08-167.png, Status 00000000, priority 5, offset 0000000000000000 length 00001000
> ```
> 
> in `CloudMirror\FileCopierWithProgress.cs` line 257
> `CfExecute(opInfo, ref opParams).ThrowIfFailed();`
> 
> System.ArgumentException:“Value does not fall within the expected range.”
> 
> ```
> Unhandled exception. System.ArgumentException: Value does not fall within the expected range.
>    at Vanara.PInvoke.HRESULT.ThrowIfFailed(String message)
>    at CloudMirror.FileCopierWithProgress.TransferData(CF_CONNECTION_KEY connectionKey, CF_TRANSFER_KEY transferKey, IntPtr transferData, Int64 startingOffset, Int64 length, NTStatus completionStatus) in CloudMirror\FileCopierWithProgress.cs:line 257
>    at CloudMirror.FileCopierWithProgress.OverlappedCompletionRoutine(UInt32 errorCode, UInt32 numberOfBytesTransfered, NativeOverlapped* overlapped) in CloudMirror\FileCopierWithProgress.cs:line 190
> ```

same to me, solve it?

**Comment by dahall** [comment]
I should have marked the `CloudMirror` project as incomplete somehow. I never got it fully working. My apologies.
